# SPDX-License-Identifier: GPL-3.0-or-later
# Automated dependency-update PRs. Python deps (requirements.txt + pyproject) and
# GitHub Actions are grouped so updates arrive as one PR per ecosystem per week.
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns: ["*"]
