#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate REFERENCE.md from source — the event schema and the detection catalog.

Both references are derived, never hand-maintained, so they cannot drift from the
code: the event schema is introspected from ``lyrebird.events`` and the detection
catalog is parsed from ``detections/sigma/``. Run after changing either.

    python scripts/gen_reference.py            # write REFERENCE.md
    python scripts/gen_reference.py --check     # exit 1 if REFERENCE.md is stale
"""
from __future__ import annotations

import dataclasses
import inspect
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SIGMA = ROOT / "detections" / "sigma"
OUT = ROOT / "REFERENCE.md"

sys.path.insert(0, str(ROOT / "src"))
from lyrebird import events  # noqa: E402


def _inline_comments(cls: type) -> dict[str, str]:
    """Map each dataclass field to its trailing ``# comment`` in the source."""
    out: dict[str, str] = {}
    for line in inspect.getsource(cls).splitlines():
        if re.match(r"\s*def ", line):
            break  # stop at the first method — only scan field declarations
            # (the leading @dataclass decorator must not trip this)
        m = re.match(r"\s*([a-z_][a-z0-9_]*)\s*:[^#]*#\s*(.+)$", line)
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out


def _field_table(cls: type) -> str:
    comments = _inline_comments(cls)
    rows = ["| Field | Type | Required | Description |", "|---|---|---|---|"]
    for f in dataclasses.fields(cls):
        required = (f.default is dataclasses.MISSING
                    and f.default_factory is dataclasses.MISSING)  # type: ignore[misc]
        typ = f.type if isinstance(f.type, str) else getattr(f.type, "__name__", str(f.type))
        desc = comments.get(f.name, "").replace("|", "\\|")  # keep table columns intact
        rows.append(f"| `{f.name}` | `{typ}` | {'yes' if required else 'no'} | {desc} |")
    return "\n".join(rows)


def _rule_tag(detection: dict) -> str:
    """Best-effort 'selects on' summary for a Sigma rule's detection block."""
    parts: list[str] = []
    for key, sel in detection.items():
        if key == "condition" or not isinstance(sel, dict):
            continue
        for field_name, val in sel.items():
            base = field_name.split("|", 1)[0]
            if base in ("tags", "request.ja3", "request.ja4"):
                vals = val if isinstance(val, list) else [val]
                parts.append(f"{base}={'/'.join(str(v) for v in vals)}")
    return "; ".join(parts) or "—"


def _detection_table() -> str:
    rows = ["| Rule | Service | Selects on | Level |", "|---|---|---|---|"]
    for path in sorted(SIGMA.glob("*.yml")):
        for doc in yaml.safe_load_all(path.read_text(encoding="utf-8")):
            if not isinstance(doc, dict) or "title" not in doc:
                continue
            title = doc.get("title", path.name)
            svc = doc.get("logsource", {}).get("service", "—")
            if "detection" in doc:
                selects = _rule_tag(doc["detection"])
            elif "correlation" in doc:
                selects = f"correlation ({doc['correlation'].get('type', '?')})"
            else:
                selects = "—"
            level = doc.get("level", "—")
            rows.append(f"| {title} | `{svc}` | `{selects}` | {level} |")
    return "\n".join(rows)


def render() -> str:
    return f"""<!-- Generated by scripts/gen_reference.py — do not edit by hand.
     Run `python scripts/gen_reference.py` to refresh. -->
# Lyrebird reference

Auto-generated from `src/lyrebird/events.py` and `detections/sigma/`. It cannot
drift from the code — a test (`tests/test_reference.py`) fails if this file is
stale. Regenerate with `python scripts/gen_reference.py`.

## Event schema (v{events.SCHEMA_VERSION})

Every emulated interaction is one JSON object on one line. This is the contract
the log files, SIEM ingestion, the analysis layer, and every Sigma rule key off.

{_field_table(events.Event)}

### Artifact

Captured payloads (uploads, mail bodies, raw socket data) are hashed, stored, and
referenced from an event's `artifacts` array.

{_field_table(events.Artifact)}

## Detection catalog

Each rule selects on a tag the emulator emits (see the event schema's `tags`).
Levels are shipped defaults — tune to your environment.

{_detection_table()}
"""


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("REFERENCE.md is stale — run: python scripts/gen_reference.py")
            return 1
        print("REFERENCE.md is up to date")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
